#!/bin/sh

DATADIR=data
TDBDIR=$DATADIR/tdb
CLDDIR=$DATADIR/cld
CHUNKDIR=$DATADIR/chunk
BEFSDIR=$DATADIR/be_fs

mkdir -p $TDBDIR
mkdir -p $CLDDIR
mkdir -p $CHUNKDIR
mkdir -p $BEFSDIR

echo 256 > $BEFSDIR/NID

cat $top_srcdir/test/users.data | ../server/tdbadm -u -C $top_srcdir/test/tabled-test.conf

if [ ! -f $TDBDIR/passwd ]
then
	rm -rf $DATADIR
	echo "test database not found."
	exit 1
fi

exit 0
