#!/bin/sh

if [ -f tabled.pid ]
then
	echo "pid file found.  daemon still running?"
	exit 1
fi

../server/tabled -P tabled.pid -d "$PWD/data" -t "$PWD/data/tdb" \
		 -p 18080 --debug

sleep 3

exit 0
