#!/bin/sh

if [ -f cld.pid ]
then
	echo "cld.pid file found.  daemon still running?"
	exit 1
fi
if [ -f chunkd.pid ]
then
	echo "chunkd.pid file found.  daemon still running?"
	exit 1
fi
if [ -f tabled.pid ]
then
	echo "tabled.pid file found.  daemon still running?"
	exit 1
fi

# May be different on Solaris... like /usr/libexec or such.
cld -d data/cld -P cld.pid -p 18081 -E
chunkd -P chunkd.pid -f $top_srcdir/test/chunkd-test.conf -E

# 3 is enough, but we like to let chunkd to come up eary and register with CLD
sleep 7

../server/tabled -P tabled.pid -C $top_srcdir/test/tabled-test.conf -E

sleep 3

exit 0
