#!/bin/sh

for d in cld chunkd tabled; do
	if [ -f $d.pid ]
	then
		echo "$d.pid file found.  daemon still running?"
		exit 1
	fi
done

# May be different on Solaris... like /usr/libexec or such.
cld -d data/cld -P cld.pid -p auto --port-file=cld.port -E

# With great sadness we have to use a delay, or else "100 s" happens.
sleep 3

chunkd -C $top_srcdir/test/chunkd-test.conf -E
../server/tabled -C $top_srcdir/test/tabled-test.conf -E

# We have a special client that waits for tabled to come online, but before
# that we also have tests that verify that the daemons started and wrote
# their PID files. So, we need to give the above daemons a chance to progress
# at least that far.
sleep 3

exit 0
