#!/bin/sh

killpid () {
	pidfile=$1
	kill $(cat $pidfile)

	for ((n = 0; n < 10; n++))
	do
		if [ ! -f $pidfile ]
		then
			return 0
		fi

		sleep 1
	done

	echo "PID file $pidfile not removed, after signal sent." >&2
	rm -f $pidfile
	return 1
}

ret=0

if [ ! -f tabled.pid ]
then
	# Just a warning. Previous test somehow made the daemon to die.
	echo "No tabled PID file found." >&2
else
	killpid tabled.pid || ret=1
fi

if [ ! -f chunkd.pid ]
then
	echo "No chunkd PID file found." >&2
else
	killpid chunkd.pid || ret=1
fi

exit "$ret"
